steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/dev-rifki-karim-ramadhan/webstat:$SHORT_SHA', '.']
  id: Building the container image

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dev-rifki-karim-ramadhan/webstat:$SHORT_SHA']
  id: Pushing the image to registry
# Deploy container image to Cloud Run

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'webstat-example', '--image', 'gcr.io/dev-rifki-karim-ramadhan/webstat:$SHORT_SHA', '--region', 'asia-southeast2', '--platform', 'managed', "--allow-unauthenticated"]