steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dev-rifki-karim-ramadhan/webstatis:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dev-rifki-karim-ramadhan/webstatis:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'webstat-example', '--image', 'gcr.io/dev-rifki-karim-ramadhan/webstatis:$SHORT_SHA', '--platform', 'managed']

images:
  - 'gcr.io/$PROJECT_ID/your-image-name:$SHORT_SHA'